name: Deploy to Cloudflare Workers

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            ANTHROPIC_API_KEY
            INSTAPAPER_USERNAME
            INSTAPAPER_PASSWORD
            TODOIST_API_TOKEN
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INSTAPAPER_USERNAME: ${{ secrets.INSTAPAPER_USERNAME }}
          INSTAPAPER_PASSWORD: ${{ secrets.INSTAPAPER_PASSWORD }}
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}

      - name: Mask deployment URL
        if: success()
        run: |
          # Mask the deployment URL to prevent it from appearing in logs
          if [ -n "${{ steps.deploy.outputs.deployment-url }}" ]; then
            echo "::add-mask::${{ steps.deploy.outputs.deployment-url }}"
            echo "Deployment successful - URL has been masked for security"
          fi
